public class Constants {
    public static final String CASE_RECORD_TYPE_NAME = 'Account Management';
    public static final String CASE_STATUS_CLOSED = 'Closed';
    public static final String CASE_TOUCHPOINT_QUARTERLY_REVIEW = 'Quarterly Review';
    public static final String CASE_TOUCHPOINT_MONTHLY_REVIEW = 'Monthly Review';
    public static final String CASE_CLOSING_OUTCOME_NO_SURVEY = 'No Survey';
    public static final String CASE_TOUCHPOINT_TYPE_SAM = 'SAM';
    public static final String CASE_TOUCHPOINT_REASON = 'Executive Reporting';
    public static final String CASE_STATUS_WORKING = 'Working';
    public static final String CASE_STATUS_NEW = 'New';
}